spring.application.name=restaurant_backend

# Thông tin k?t n?i MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/restaurant2?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=080306@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# C?u hình JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tùy ch?n: T?i ?u batch insert/update
spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true